version: '3'
services:
  logic:
    build: .
    ports:
      - "2000:2000"
  api_service:
    build: ./src/frcm/API
    ports:
      - "8000:8000"
    tty: true
    stdin_open: true
    depends_on:
      - logic