name: Deploy to Google Cloud VM

on:
  push:
    branches:
      - main  # or the branch you want to deploy from

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.GCP_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan ${{ secrets.GCP_VM_IP }} >> ~/.ssh/known_hosts

    - name: Deploy to Google Cloud VM
      run: |
        ssh -i ~/.ssh/id_rsa ${{ secrets.GCP_USER }}@${{ secrets.GCP_VM_IP }} << 'EOF'
          docker pull haakonm/fireguard-app:latest
          docker stop fireguard-app-instance || true
          docker rm fireguard-app-instance || true
          docker run -d --name fireguard-app-instance \
          -e MET_CLIENT_ID="${{ secrets.MET_CLIENT_ID }}" \
          -e MET_CLIENT_SECRET="${{ secrets.MET_CLIENT_SECRET }}" \
          -e FIREBASE_CREDENTIALS_BASE64="${{ secrets.FIREBASE_CREDENTIALS_BASE64 }}" \
          -p 9005:8000 haakonm/fireguard-app:latest
        EOF