name: SonarQube Scan

on:
  push:

jobs:
  Sonarqube-scan:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the code
      uses: actions/checkout@v4

    - name: Run SonarScanner using Docker
      run: |
        docker run \
          --rm \
          -e SONAR_HOST_URL="http://${{ secrets.SONARQUBE_URL }}" \
          -e SONAR_SCANNER_OPTS="-Dsonar.projectKey=${{ secrets.SONARQUBE_PROJECT_KEY }}" \
          -e SONAR_TOKEN="${{ secrets.SONAR_TOKEN }}" \
          -v "${{ github.workspace }}:/usr/src" \
          sonarsource/sonar-scanner-cli